### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/map-component#43]
Add some tests!

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by p-a-s-c-a-l** [comment]
>     console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Cross origin http://localhost forbidden
          at dispatchError (C:\git_work\CLARITY\map-component\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:65:19)
          at Object.validCORSHeaders (C:\git_work\CLARITY\map-component\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:77:5)
          at receiveResponse (C:\git_work\CLARITY\map-component\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:847:21)
          at Request.client.on.res (C:\git_work\CLARITY\map-component\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:679:38)
          at Request.emit (events.js:198:13)
          at Request.onRequestResponse (C:\git_work\CLARITY\map-component\node_modules\request\request.js:1066:10)
          at ClientRequest.emit (events.js:198:13)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
          at Socket.socketOnData (_http_client.js:442:20) undefined
    console.log ../csis-helpers-js/dist/index.js:171
      18 resources left after filtering 32 resources by tag type taxonomy_term--eu_gl and tag name Hazard Characterization - Local Effects
    console.log ../csis-helpers-js/dist/index.js:171
      10 resources left after filtering 32 resources by tag type taxonomy_term--eu_gl and tag name Hazard Characterization
    console.warn ../csis-helpers-js/dist/index.js:264
      no references found in resource 'Adaptation Options' (9c62e7d3-33c8-41a6-825f-9da36d6d7bda)
    console.log ../csis-helpers-js/dist/index.js:270
      30 resources left after filtering 32 resources by reference type @mapview:ogc:wms
    console.log ../csis-helpers-js/dist/index.js:171
      10 resources left after filtering 32 resources by tag type taxonomy_term--eu_gl and tag name Hazard Characterization
    console.log ../csis-helpers-js/dist/index.js:270
      10 resources left after filtering 10 resources by reference type @mapview:ogc:wms
    console.log ../csis-helpers-js/dist/index.js:171
      10 resources left after filtering 32 resources by tag type taxonomy_term--eu_gl and tag name Hazard Characterization
    console.log ../csis-helpers-js/dist/index.js:270
      10 resources left after filtering 10 resources by reference type @mapview:ogc:wms

**Comment by p-a-s-c-a-l** [comment]
Plus the same problem as here: https://github.com/clarity-h2020/simple-table-component/issues/4

It's always 'nice' to see your tests failing not because of changes in code or tests specs but in the test environment itself. 😲

**Comment by p-a-s-c-a-l** [comment]
Fix: https://github.com/techieanant

**Comment by p-a-s-c-a-l** [comment]
`log.debug()` in `beforeAll` is not printed  to console when running the tests in VSCode.

**Comment by p-a-s-c-a-l** [comment]
❓  ❓  ❓

 TypeError: Cannot read property 'close' of undefined

      169 | afterAll(() => {
      170 |     log.debug('afterAll');
    > 171 |     server.close(() => {
          |            ^
      172 |             //console.log('JSON Server closed');
      173 |             //process.exit(0);
      174 |     });

**Comment by p-a-s-c-a-l** [comment]
FUBAR:

> Test Suites: 1 failed, 2 passed, 3 total
Tests:       8 failed, 3 skipped, 4 passed, 15 total
Snapshots:   0 total
Time:        17.741s
Ran all test suites related to changed files.

**Comment by p-a-s-c-a-l** [comment]
don't expect that this will work on an ip6 capable system if server adress is `::1`
> http://${server.address().address}:${server.address().port}

hard-code `http://localhost:${server.address().port}` instead. 👎

**Comment by p-a-s-c-a-l** [comment]
Works locally but not on CI:

FAIL src/__tests__/CSISRemoteHelpers.test.js (12.224s)
  ● Console

    console.warn src/__tests__/CSISRemoteHelpers.test.js:76
      no headers ENV VAR (.env.test.local) found, skipping remote API tests
    console.warn src/__tests__/CSISRemoteHelpers.test.js:113
      no headers.js fixture found, skipping remote API tests
    console.log node_modules/csis-helpers-js/dist/index.js:983
      fetching study from CSIS API: https://csis.myclimateservice.eu/jsonapi/group/study/c3609e3e-f80f-482b-9e9f-3a26226a6859?include=field_data_package,field_data_package.field_resources,field_data_package.field_resources.field_resource_tags,field_data_package.field_resources.field_references,field_data_package.field_resources.field_resource_tags.field_var_meaning2
    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Cross origin http://localhost forbidden
          at dispatchError (/var/jenkins_home/workspace/map-component/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at Object.validCORSHeaders (/var/jenkins_home/workspace/map-component/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:77:5)
          at receiveResponse (/var/jenkins_home/workspace/map-component/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:847:21)
          at Request.<anonymous> (/var/jenkins_home/workspace/map-component/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:679:38)
          at Request.emit (events.js:321:20)
          at Request.onRequestResponse (/var/jenkins_home/workspace/map-component/node_modules/request/request.js:1066:10)
          at ClientRequest.emit (events.js:321:20)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
          at TLSSocket.socketOnData (_http_client.js:479:22) undefined
    console.error node_modules/csis-helpers-js/dist/index.js:996
      could not fetch study from https://csis.myclimateservice.eu/jsonapi/group/study/c3609e3e-f80f-482b-9e9f-3a26226a6859?include=field_data_package,field_data_package.field_resources,field_data_package.field_resources.field_resource_tags,field_data_package.field_resources.field_references,field_data_package.field_resources.field_resource_tags.field_var_meaning2 Error: Network Error

**Comment by p-a-s-c-a-l** [comment]
BTW, remote tests shouldn't be executed on CI, because `.env.test.local` is no present.!
It seems that `it.only`doesn't work any more as expected.
